services:
  db:
    image: mysql:8.0
    container_name: mundiales_db
    restart: unless-stopped
    command: --default-time-zone=-06:00
    environment:
      TZ: America/Guatemala
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: mundiales
      MYSQL_USER: mundiales_user
      MYSQL_PASSWORD: mundiales1234
    ports:
      - "3306:3306"
    volumes:
      - ./init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mundiales_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot1234"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mundiales_data:
